[user]
name = "Mark Nichols"
email = "mark@zanshin.net"

# [merge-tools.opendiff]
# program = "jj-opendiff"
# merge-args = ["$base", "$left", "$right", "$output"]

[ui]
color = "auto"
default-command = "status"
editor = "nvim"
# diff-formatter = ":git"
diff-editor = ":builtin"
# merge-editor = "jj-opendiff"

[colors]
commit_id = "blue"
change_id = "red"
prefix = { bold = true }
rest = "#566573"
# "working_copy commit_id" = { underline = true }

[aliases]
# Find the closest ancestor with a bookmark pointing at it, and move it to the
# parent of the working copy.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
long = ["log", "-T", "builtin_log_detailed"]
short = ["log", "-T", "builtin_log_oneline"]

[template-aliases]
'format_short_signature(signature)' = "signature"
'format_timestamp(timestamp)' = "timestamp.ago()"
'format_short_id(id)' = "id.shortest(12)"
# 'format_short_id(id)' = 'id.shortest(12).prefix() ++ "[" ++ id.shortest(12).rest() ++ "]"'

