# My tweaks

add_newline = true
format = '$all'
# right_format = """$all"""
command_timeout = 750

[hostname]
ssh_only = true
ssh_symbol = ""
format = "on [$hostname](red) "
disabled = false

[directory]
truncation_length = 5
truncation_symbol = '.../'
truncate_to_repo = false
style = "blue"

[username]
style_user = 'blue'
style_root = 'red bold'
format = '[$user]($style) '
# format = '\[[$user]($style)\]'
disabled = false
show_always = false
