# prompt wide configuration settings
add_newline = true
command_timeout = 750

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
format = '[$user]($style) '

[hostname]
ssh_symbol = ""
format = "on [$hostname](red) "

[directory]
style = "blue"

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[git_branch]
format = "[$branch ]($style)"
style = "#ffb454"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "="
untracked = "⇡"
modified = "⇣"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#d2a6ff"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# [python]
# format = "[$virtualenv]($style) "
# style = "bright-black"
#

# ---------
# My tweaks
# ---------
#
# add_newline = true
# # format = '$all'
# # right_format = """$all"""
# command_timeout = 750
#
# [hostname]
# ssh_only = true
# ssh_symbol = ""
# format = "on [$hostname](red) "
# disabled = false
#
# # [directory]
# # truncation_length = 5
# # truncation_symbol = '.../'
# # truncate_to_repo = false
# # style = "blue"
# #
# [username]
# style_user = 'blue'
# style_root = 'red bold'
# format = '[$user]($style) '
# # format = '\[[$user]($style)\]'
# disabled = false
# show_always = false
#
# # Display warning when in PROD Kubernetes context
# # [custom.k8_prod_warning]
# # description = 'Shows an indicator when the name of the current kubectl context contains `prod`'
# # when = 'kubectl config current-content | grep -qi prod'
# # command = 'echo " on PROD"'
# # symbol = '⚠️ '
# # style = 'bold red'
# # format = '[$symbol($output )]($style)'
#
# [aws]
# disabled = true
